# This file provides instructions for packaging.

`Attribute-QueueStack`
	perl_version_from m`Attribute::QueueStack`;
	version_from      m`Attribute::QueueStack`;
	readme_from       m`Attribute::QueueStack`;
	requires          p`Attribute::Handlers`;
	test_requires     p`Test::More 0.96`;
	test_requires     p`Test::Fatal`;
	.

